services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"            # LocalStack API Gateway
      - "4510-4559:4510-4559"  # external services port range
    environment:
      - SERVICES=sqs
      - DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - LOCALSTACK_AUTH_TOKEN=ls-sumeGixo-3255-LUQI-poXI-YAGI38464eff